blog/urls.py
from django.urls import path
from . import views
from .feeds import LatestPostsFeed


app_name = 'blog'

urlpatterns = [
    path('', views.post_list, name='post_list'),
    path('tag/<slug:tag_slug>/', views.post_list, name='post_list_by_tag'),
    # path('', views.PostListView.as_view(), name='post_list'),
    path('<int:year>/<int:month>/<int:day>/<slug:post>/', views.post_detail, name='post_detail'),
    path('<int:post_id>/share/', views.post_share, name='post_share'),
    path('feed/', LatestPostsFeed(), name='post_feed'),
    path('search/', views.post_search, name='post_search'),
]

blog/models.py
from django.db import models
from django.urls import reverse
from django.utils import timezone
from django.contrib.auth.models import User

# Создание своего менеджера модели взамен objects
from taggit.managers import TaggableManager


class PublishedManager(models.Manager):
    def get_queryset(self):
        return super().get_queryset().filter(status='published')


class Post(models.Model):
    STATUS_CHOICES = (
        ('draft', 'В разработке'),
        ('published', 'Опубликовано'),
    )
    title = models.CharField(max_length=200, verbose_name='Название статьи')
    slug = models.SlugField(max_length=200, unique_for_date='publish')
    author = models.ForeignKey(User, on_delete=models.CASCADE, related_name='blog_posts',
                               verbose_name='Автор')
    body = models.TextField(verbose_name='Поле для статьи')
    publish = models.DateTimeField(default=timezone.now, verbose_name='Дата публикации')
    created = models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')
    update = models.DateTimeField(auto_now=True, verbose_name='Дата редактирования')
    status = models.CharField(max_length=10, choices=STATUS_CHOICES, default='draft', verbose_name='Статус')
    objects = models.Manager()  # Менеджер по умолчанию
    published = PublishedManager()  # Мой новый менеджер
    tags = TaggableManager(verbose_name="Тэги")  # Для тэгов статей

    def get_absolute_url(self):
        """Для получения ссылок на статью"""
        return reverse('blog:post_detail', args=[self.publish.year, self.publish.month, self.publish.day,
                                                 self.slug])

    def __str__(self):
        return self.title

    class Meta:
        ordering = ('-publish',)
        verbose_name = 'Статья'
        verbose_name_plural = 'Статьи'


# Модель комментария
class Comment(models.Model):
    post = models.ForeignKey(Post, on_delete=models.CASCADE, related_name='comments', verbose_name='Статья')
    name = models.CharField(max_length=80, verbose_name='Имя')
    email = models.EmailField()
    body = models.TextField(verbose_name='Комментарий')
    created = models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')
    update = models.DateTimeField(auto_now=True, verbose_name='Дата редактирования')
    active = models.BooleanField(default=True)

    def __str__(self):
        return 'Комментарий {} к статье {}'.format(self.name, self.post)

    class Meta:
        ordering = ('created',)
        verbose_name = 'Комментарий'
        verbose_name_plural = 'Комментарии'

blog/forms.py
from django import forms

from .models import Comment


class EmailPostForm(forms.Form):
    name = forms.CharField(max_length=25)
    email = forms.EmailField()
    to = forms.EmailField()
    comments = forms.CharField(required=False, widget=forms.Textarea)


class CommentForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields = ('name', 'email', 'body')


class SearchForm(forms.Form):
    query = forms.CharField()

blog/views.py
from django.contrib.postgres.search import SearchVector, SearchQuery, SearchRank, TrigramSimilarity
from django.core.mail import send_mail
from django.db.models import Count
from django.shortcuts import render, get_object_or_404
from taggit.models import Tag

from .models import Post, Comment

from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger

from django.views.generic import ListView

from .forms import EmailPostForm, CommentForm, SearchForm


def post_list(request, tag_slug=None):
    """Выводит страницу со списком статей с тэгами и пагинацией"""
    object_list = Post.published.all()

    # Добавляем возможность сортировки статей по тэгам
    tag = None
    if tag_slug:
        tag = get_object_or_404(Tag, slug=tag_slug)
        object_list = object_list.filter(tags__in=[tag])

    paginator = Paginator(object_list, 3)  # выводит по 3 статьи на каждой странице
    page = request.GET.get('page')
    try:
        posts = paginator.page(page)
    except PageNotAnInteger:
        # Если страница не является целым числом, возвращает первую страницу
        posts = paginator.page(1)
    except EmptyPage:
        # Если номер страницы больше, чем общее количество страниц, возвращаем последнюю
        posts = paginator.page(paginator.num_pages)
    return render(request, 'blog/post/list.html', {'page': page,
                                                   'posts': posts,
                                                   'tag': tag})


# class PostListView(ListView):
#     queryset = Post.published.all()
#     context_object_name = 'posts'
#     paginate_by = 3
#     template_name = 'blog/post/list.html'


def post_detail(request, year, month, day, post):
    """Выводит страницу со статьей и комментариями к ней"""
    post = get_object_or_404(Post, slug=post, status='published', publish__year=year, publish__month=month,
                             publish__day=day)
    # Список активных комментариев для этой статьи
    comments = post.comments.filter(active=True)
    new_comment = None
    if request.method == 'POST':
        # Пользователь отправил комментарий
        comment_form = CommentForm(data=request.POST)
        if comment_form.is_valid():
            # Создаём комментарий, но пока не сохраняем в базе данных
            new_comment = comment_form.save(commit=False)
            # привязываем комментарий к текущей статье
            new_comment.post = post
            # Сохраняем комментарий в базе данных
            new_comment.save()
    else:
        comment_form = CommentForm()

    # формирование списка похожих статей
    post_tags_ids = post.tags.values_list('id', flat=True)
    similar_posts = Post.published.filter(tags__in=post_tags_ids).exclude(id=post.id)
    similar_posts = similar_posts.annotate(same_tags=Count('tags')).order_by('-same_tags', '-publish')[:4]
    return render(request, 'blog/post/detail.html', {'post': post,
                                                     'comments': comments,
                                                     'new_comment': new_comment,
                                                     'comment_form': comment_form,
                                                     'similar_posts': similar_posts})


def post_share(request, post_id):
    """Обработка данных формы и отправка их на почту"""
    # Получение статьи по идентификатору
    post = get_object_or_404(Post, id=post_id, status='published')
    sent = False
    if request.method == 'POST':
        # Форма отправлена на сохранение
        form = EmailPostForm(request.POST)
        if form.is_valid():
            # Все поля формы прошли валидацию
            cd = form.cleaned_data
            # Отправка электронной почты
            post_url = request.build_absolute_uri(post.get_absolute_url())
            subject = '{} ({}) рекомендует Вам прочитать "{}"'.format(cd['name'], cd['email'], post.title)
            message = 'Прочитай "{}" об {}\n\n комментарий {}\`s: {}'.format(post.title, post_url, cd['name'],
                                                                             cd['comments'])
            send_mail(subject, message, 'admin@myblog.com', [cd['to']])
            sent = True
    else:
        form = EmailPostForm()
    return render(request, 'blog/post/share.html', {'post': post, 'form': form, 'sent': sent})


def post_search(request):
    """Реализация поиска"""
    form = SearchForm()
    query = None
    results = []
    if 'query' in request.GET:
        form = SearchForm(request.GET)
        if form.is_valid():
            query = form.cleaned_data['query']
            search_vector = SearchVector('title', 'body')
            search_query = SearchQuery(query)
            results = Post.objects.annotate(search=search_vector, rank=SearchRank(search_vector, search_query)
                                            ).filter(search=search_query).order_by('-rank')
            # results = Post.objects.annotate(similarity=TrigramSimilarity('title', query),
            #                                 ).filter(similarity__gt=0.3).order_by('-similarity')
    return render(request, 'blog/post/search.html', {'form': form,
                                                     'query': query,
                                                     'results': results})

blog/templates/blog/post/detail.html
{% extends 'blog/base.html' %}

{% load blog_tags %}

{% block title %}{{ post.title }}{% endblock %}

{% block content %}
    <h1>{{ post.title }}</h1>
    <p class="tags">
            Тэги:
            {% for tag in post.tags.all %}
                <a href="{% url 'blog:post_list_by_tag' tag.slug %}">{{ tag.name }}</a>
                {% if not forloop.last %}, {% endif %}
            {% endfor %}
        </p>
    <p class="date">Опубликовано: {{ post.publish }} | Автор: {{ post.author }}</p>
    {{post.body|markdown}}

    <p><a href="{% url 'blog:post_share' post.id %}">Поделиться статьёй</a></p>

    <h3>Рекомендуемые статьи</h3>
    {% for similar_post in similar_posts %}
        <p><a href="{{ similar_post.get_absolute_url }}">{{ similar_post }}</a></p>
    {% endfor %}

    {% with comments.count as total_comments %}
        <h2>{{ total_comments }} comment{{total_comments|pluralize}}</h2>
    {% endwith %}

    {% for comment in comments %}
        <div class="comment">
            <p class="info">
                Комментарий {{ forloop.counter }}
            </p>
            <p>{{ comment.name }} {{ comment.created }} </p>
            <p>{{ comment.body|linebreaks }}</p>
            <hr>
        </div>
    {% empty %}
        <p>Комментариев пока нет.</p>
    {% endfor %}

    {% if new_comment %}
        <h2>Ваш комментарий был добавлен.</h2>
    {% else %}
        <h2>Добавьте новый комментарий</h2>
        <form action="." method="post">
            {{ comment_form.as_p }}
            {% csrf_token %}
            <p><input type="submit" value="Добавить комментарий"></p>
        </form>
    {% endif %}

    <p><a href="{% url 'blog:post_list' %}">Назад к списку</a></p>
{% endblock %}

blog/templates/blog/post/latest_posts.html
<ul>
    {% for post in latest_posts %}
        <li><a href="{{ post.get_absolute_url }}">{{ post.title }}</a></li>
    {% endfor %}
</ul>

blog/templates/blog/post/list.html
{% extends 'blog/base.html' %}

{% load blog_tags %}

{% block title %}Мой блог{% endblock %}

{% block content %}
    <h1>Мой блог</h1>

    {% if tag %}
        <h2>Сообщения, помеченные "{{ tag.name }}"</h2>
    {% endif %}

    {% for post in posts %}
        <h2>
            <a href="{{ post.get_absolute_url }}">{{ post.title }}</a>
        </h2>
<!--        <p class="tags">Тэги: {{ post.tags.all|join:", " }}</p>-->
        <p class="tags">
            Тэги:
            {% for tag in post.tags.all %}
                <a href="{% url 'blog:post_list_by_tag' tag.slug %}">{{ tag.name }}</a>
                {% if not forloop.last %}, {% endif %}
            {% endfor %}
        </p>
        <p class="date">Опубликовано: {{ post.publish }} | Автор: {{ post.author }}</p>
        {{ post.body|markdown|truncatewords_html:30 }}

    {% endfor %}
    {% include 'blog/post/pagination.html' with page=posts %}
{% endblock %}

blog/templates/blog/post/pagination.html
<div class="pagination">
  <span class="step-links">
    {% if page.has_previous %}
      <a href="?page={{ page.previous_page_number }}">Предыдущая</a>
    {% endif %}
    <span class="current">
      Страница {{ page.number }} из {{ page.paginator.num_pages }}
    </span>
    {% if page.has_next %}
      <a href="?page={{ page.next_page_number }}">Следующая</a>
    {% endif %}
  </span>
</div>

blog/templates/blog/post/search.html
{% extends 'blog/base.html' %}

{% load blog_tags %}

{% block title %}Поиск{% endblock %}

{% block content %}
    {% if query %}
        <h1>Статьи, содержащие "{{ query }}"</h1>
        <h3>
            {% with results.count as total_results %}
                Найдено результатов - {{ total_results }}
            {% endwith %}
        </h3>
        {% for post in results %}
            <h4><a href="{{ post.get_absolute_url }}">{{ post.title }}</a></h4>
            {{ post.body|markdown|truncatewords_html:5 }}
        {% empty %}
            <p>Результатов по вашему запросу нет.</p>
        {% endfor %}
        <p><a href="{% url 'blog:post_search' %}">Повторите поиск</a></p>
    {% else %}
        <h1>Поиск статей</h1>
        <form action="." method="get">
            {{ form.as_p }}
            <input type="submit" value="Поиск">
        </form>
    {% endif %}
{% endblock %}

blog/templates/blog/post/share.html
{% extends 'blog/base.html' %}

{% block title %}Поделиться публикацией{% endblock %}

{% block content %}
    {% if sent %}
        <h1>Электронное письмо успешно отправлено</h1>
        <p>"{{ post.title }}" был успешно отправлен в {{ form.cleaned_data.to }}.</p>
        <p><a href="{% url 'blog:post_list' %}">Назад к списку</a></p>
    {% else %}
        <h1>Поделитесь "{{ post.title }}" по электронной почте</h1>
        <form action="." method="post">
            {{ form.as_p }}
            {% csrf_token %}
            <input type="submit" value="Отправить">
        </form>
    {% endif %}
{% endblock %}